### ISSUE TITLE
Tree padding-right increase

### ISSUE THREAD

**Issue by nukkamoto** [olmokramer/atom-autohide-tree-view#1]
IMO I would increase the padding a little bit on the right leave some white space as it makes ma want to increase the size of the tree, it looks a bit unnatural.

Other than that it works like a charm :) cheers.

**Comment by olmokramer** [comment]
Hi, thanks for the feedback! :)

That's a good point, only it causes some space on the right side next to selected items. This image probably explains it better than I can :p
![atom-autohide-tree-view-padding-right](https://cloud.githubusercontent.com/assets/3612514/5978696/0c4270ec-a8a2-11e4-919c-893cb28e3535.png)

I'll make it an option for those that don't care about that

**Comment by olmokramer** [comment]
I just released version 0.4.0, which adds an option to set some extra padding on the right side of the tree view.

**Comment by olmokramer** [comment]
Update: I removed the setting again, because it is so trivial to add in your `~/.atom/styles.less`:

```
.tree-view-resizer .tree-view {
  padding-right: 20px;
}
```

**Comment by olmokramer** [comment]
Or use `padding-left` if you have the tree-view on the right side of the screen

**Comment by nukkamoto** [comment]
you are probably right :)
