### ISSUE TITLE
feature request - make pushing text to right an option

### ISSUE THREAD

**Issue by mark-hahn** [olmokramer/atom-autohide-tree-view#10]
I know someone else said they liked the text under the bar not pushing to the right but it has been causing me trouble.  I have had times when I wanted to see the text while the treeview was open.  Also I've had trouble editing the text before the treeview closed, but I don't remember the details.

I guess this is a personal opinion which is why I'm requesting a feature.

**Comment by olmokramer** [comment]
v0.15.0 adds this option, `pushEditor`. The text editing problem is probably because the tree view gets focused when it's opened. I can also add a setting for that if you want?
