### ISSUE TITLE
Tree view file operations don't focus on modal input.

### ISSUE THREAD

**Issue by gepoch** [olmokramer/atom-autohide-tree-view#11]
When I'm in tree view, normally I'm able to create and move files using 'a' and 'm' respectively.

Highlighting a folder name, and typing `a` presents me with a modal text input (which takes focus away from the tree view,) prompting me for the name of the file that I want to create.

When using atom-autohide-tree-view, this modal still appears, but focus moves back into the editor. 

![screenshot from 2015-03-04 09 04 06](https://cloud.githubusercontent.com/assets/967166/6486087/18f91546-c24e-11e4-86d6-f2bab83a28ec.png)

This isn't a big deal, as I just need to click in the modal input, and type the new filename, but it's a hiccup to have to switch to my mouse in the middle of my keyboard driven workflow.

Thanks so much for the plugin! It's been a nice space-saver, and it looks really slick!

**Comment by olmokramer** [comment]
Hey you're right... I'll look into it somewhere this weekend.

And thanks for the kind words! :)

**Comment by olmokramer** [comment]
It was a pretty easy fix, just published `v0.15.4` that should fix this. Please let me know if it works

**Comment by gepoch** [comment]
Fantastic! That's working perfectly, now.

Thanks!
