### ISSUE TITLE
Conflicts with symbols-tree-view

### ISSUE THREAD

**Issue by ghost** [olmokramer/atom-autohide-tree-view#12]
The package `symbols-tree-view` puts an auto-hiding panel on the right side of the atom window, but when this package is enabled I can't get `symbols-tree-view` to reveal itself. Would be nice if they could both auto-hide at the same time, saving me space.

**Comment by olmokramer** [comment]
Hmm this package shouldn't interfere with the symbols tree view. I specifically target the tree view element supplied by the actual `tree-view` package. How do you trigger the `symbols-tree-view`? Using the `Symbols Tree View: Toggle` command from the command palette works fine for me.

Nonetheless, it's a great idea to add support for `symbols-tree-view`. I'll look into that sometime, but I'm extremely busy right now. So if you want to give it a try... :)

**Comment by ghost** [comment]
Ah yeah, sorry I wasn't clear. The default settings for `symbols-tree-view` are ok, but if you set it to auto-hide, then what should in theory happen is that both `symbols-tree-view` and `autohide-tree-view` should reveal themselves automatically with a mouseover, but most of the time `symbols-tree-view` won't respond to the hover when `autohide-tree-view` is active. It's a bit fiddly though, I got it to open a couple times. If it works for you on the first try, try restarting atom and see if it still works. It's weird.

**Comment by olmokramer** [comment]
Ok thanks for clarifying. I'll try that. Still this shouldn't happen because i listen on the tree view for hover events...

**Comment by olmokramer** [comment]
I get it too, but it doesn't seem to have anything to do with this package. It seems to be a combination of `symbols-tree-view`'s `autoHide` and `autoToggle` that breaks the package's autohide. What I did:
1. Disable `autohide-tree-view` <em>and</em> `symbols-tree-view` and delete both their configs manually from `config.cson`
2. Reload Atom
3. Enable `symbols-tree-view`, leave the defaults and the package seems to work fine
4. Reload Atom, `symtols-tree-view` still works just fine
5. Enable `symbols-tree-view`'s autohide, it works fine
6. Reload Atom (again), the autohide still works fine
7. Enable `symbols-tree-view`'s autotoggle
8. `symbols-tree-view`'s autohide is now broken

Is this the issue you're talking about? Do you have both `autoHide` and `autoToggle` enabled in `symbols-tree-view`? Can you reproduce this?

I'll at least file this bug there.

**Comment by olmokramer** [comment]
Bug filed here: https://github.com/xndcn/symbols-tree-view/issues/24

**Comment by ghost** [comment]
Huh, indeed you're right, I was using `autoHide` and `autoToggle` together and that combination breaks even without `autohide-tree-view` active. 

For some reason in my initial troubleshooting it was able to work but then apparently just by coincidence it stopped working when I enabled `autohide-tree-view`. Funny how I'm now able to reproduce without your package at all...

**Comment by olmokramer** [comment]
The issue in the `symbols-tree-view` package should be fixed now.

**Comment by ghost** [comment]
Wow, it is working! Thanks for following that up ;-)
