### ISSUE TITLE
Issue with new file

### ISSUE THREAD

**Issue by denysbutenko** [olmokramer/atom-autohide-tree-view#13]
I can't create a new file or duplicate existing while activated auto-hiding of treeview.

If run `Autohide Tree View: Show` then try again create a new file, that's works fine or if disable this package.

OS X Mavericks
Atom: 0.187.0
autohide-tree-view: 0.15.5

**Comment by olmokramer** [comment]
How do you create the new file? With the `a` keybinding on the tree view? Or with the right-click context menu? Or from the command palette `Tree View: Add File`?

And what exactly does not work? Does it not show the popup with the filename?

**Comment by denysbutenko** [comment]
Yep, you're right! With the right-click context-menu. It doesn't show the popup with the filename.
With `a` hotkey working fine and also with the command palette too.

**Comment by olmokramer** [comment]
Hmm.. I can't reproduce this. Does the tree view also hide when you click `New File` in the context menu?

Could you please list the packages you have installed? run `apm list -bip` from the command line and post the results here.

**Comment by denysbutenko** [comment]
I've recorded a video: https://dl.dropboxusercontent.com/u/10265045/auto-tree-hide.mov

``` Sublime-Style-Column-Selection@1.2.3
atom-beautify@0.22.3
atom-color-highlight@3.0.8
auto-update-packages@0.2.2
autoclose-html@0.15.0
autocomplete-paths@1.0.2
autocomplete-plus@2.6.0
autohide-tree-view@0.15.5
close-tags@0.2.0
editorconfig@0.3.3
emmet@2.3.4
expand-selection-to-quotes@0.1.0
file-icons@1.5.1
html-entities@0.3.1
html-helper@0.2.3
html-img@0.3.2
javascript-snippets@1.0.0
language-nunjucks@1.3.0
language-smarty-php@0.5.0
linter@0.12.0
minimap@4.6.0
open-last-project@0.3.4
project-manager@1.15.5
project-switcher2@0.2.8
sassbeautify@0.2.0
slash-closer@0.7.1
```

**Comment by olmokramer** [comment]
Thanks! That's really helpful! I'm afraid I don't have time to look at this until the weekend, so you'll have to do with the keyboard shortcut for a few days.

I can also recommend you the [advanced-new-file](https://atom.io/packages/advanced-new-file) package for file/folder creation. It's awesome! :)

**Comment by olmokramer** [comment]
I can't reproduce this. Does it also happen with all other packages disabled?

**Comment by denysbutenko** [comment]
It seems that I found the cause.
If change theme from the `One Dark` to `Atom Dark` - works fine.
If we have activated theme `One Dark` and move cursor at least by one pixel the newfile popup disappears.

PS: I'll create issue directly in the `One Dark` repository.

**Comment by olmokramer** [comment]
I don't think this is an issue with the `One Dark` theme, but rather with my package. I still don't have time to look at the issue until next weekend, so you'll have to wait a few more days.

Cheers!

**Comment by olmokramer** [comment]
I just published `v0.16.0` and I think it should be more stable than previous versions. I was getting the same issue with the `One Dark` theme, and they seem to be fixed now. Please let me know if it works.
Cheers

**Comment by denysbutenko** [comment]
It works fine. Thanks.

**Comment by olmokramer** [comment]
That was fast :0

**Comment by maxigaz** [comment]
I've had the exact same problem since last update (0.22.0). Just like in @denysbutenko's screencast, the add new file, new folder, and duplicate commands do nothing when they are clicked in the context menu and autohide is enabled. The only difference on my side is that when I click on one of these commands, the tree view hides immediately.

Here's my list of installed packages:

```
advanced-new-file@0.4.3
atom-beautify@0.28.8
atom-html-preview@0.1.10
autocomplete-paths@1.0.2
autocomplete-php@0.3.6
autohide-tree-view@0.22.0
change-case@0.6.0
color-picker@2.0.11
emmet@2.3.12
file-icons@1.5.8
html-entities@0.4.0
last-cursor-position@0.9.0
php-cs-fixer@2.3.0
project-manager@1.15.11
punchclock@0.6.0
tabs-to-spaces@0.11.0
webbox-color@0.5.8
```

PS: Using Atom 1.0.2 for Linux.

**Comment by olmokramer** [comment]
@notargets I think that is a duplication of #28. I haven't found the problem or a solution yet, but please continue discussion in that issue :) Thanks!

(Also, could you try disabling the Emmet package, and try again? Emmet is known to cause some seemingly random issues in Atom...)

**Comment by maxigaz** [comment]
Oh, OK, sorry about that.

(Disabling Emmet doesn't seem to make a difference, by the way.)
