### ISSUE TITLE
0.16 focusing behavior!

### ISSUE THREAD

**Issue by gepoch** [olmokramer/atom-autohide-tree-view#15]
Hey! I noticed that in 0.16, auto focusing has been removed!

This breaks my workflow a bit, unfortunately. Would it be possible to bring this back as a setting? I enjoyed being able to open the tree and focus on it with a single key combo.

Thanks!

**Comment by gepoch** [comment]
As a workaround, I can toggle with ctrl-\ and then switch back-and-forth with ctrl-0, but it's a bit awkward. The only time I open the treeview is when I want to operate on or browse in it!

**Comment by olmokramer** [comment]
Problem is, the tree view focusing is a bit awkward. I'll bring it back as an option, but it might cause some issues with focusing other parts of the editor, such as the popup when you create a new file from the tree view. Expect an update in a few minutes.

**Comment by olmokramer** [comment]
New version is up! It has two extra settings, `focusTreeViewOnOpen` and `unfocusTreeViewOnClose`

**Comment by gepoch** [comment]
Working perfectly! Thanks for the quick turnaround :)

**Comment by olmokramer** [comment]
You're welcome :) Glad to hear it works
