### ISSUE TITLE
zone of triggering

### ISSUE THREAD

**Issue by denysbutenko** [olmokramer/atom-autohide-tree-view#16]
Hey!

I have issue with the showing of treeview after upgrade to Yosemite . Or regardless of that.
If move cursor to the corner of the window (showed up the resize cursor) but treeview didn't triggered.

```
Atom: 0.190.0
Package: 0.16.3
OS X: 10.10.3
```

https://dl.dropboxusercontent.com/u/10265045/auto-tree-hide-show-issue.mov

**Comment by olmokramer** [comment]
Thanks for the report (and the video :+1:) I think that's just how OSX handles windows. Is the window maximized?

**Comment by denysbutenko** [comment]
Yeah, checked a few times (using Spectacle).

**Comment by olmokramer** [comment]
I'm afraid I can't do much about this. If OSX wants you to be able to resize the maximized window, then who am I to go against them ;) Maybe you can try moving the window 1px off-screen

Just out of curiosity, does this also happen with the tree view on the left side? And how about fullscreen mode?

**Comment by denysbutenko** [comment]
I tried to resize manually and nothing.

It works fine on the left side. Triggered properly with the resize cursor.
In the fullscreen mode same behavior. Left side - ok, right side - not ok.
I noticed changes when I enable 'Show on Right Side'. Added 2-3px margin from both side.

Also noticed have 3-5 dead pixels on right side, not just one.
You can see it: https://dl.dropboxusercontent.com/u/10265045/autohide-treeview-right-side.mov

**Comment by olmokramer** [comment]
Hmmm... That definitely looks weird and wrong. Would you please provide me with the following information:
- The themes (both UI and syntax) you are using?
- The config for `autohide-tree-view`
- The config for `tree-view`
- A list of packages you are using. You can get this by running `apm list --installed` from the terminal.

Does this also happen with older versions of `autohide-tree-view`? You can install a specific version by appending `@x.x.x` to the package name, `apm install autohide-tree-view@0.15.5` for example.

**Comment by denysbutenko** [comment]
It's affected only on the `One Dark` theme. Regardless of syntax theme. I tried change theme UI to Seti and all works fine.

Theme UI:  `One Dark`
Theme Syntax: `Seti`

Config of the `autohide-tree-view` package:
`Show delay:  0`
rest of options by default.

Config of the `tree-view` package:
- [ ] Hide Ignored Names
- [ ] Hide VCS Ignored Files
- [x] Show On Right Side
- [x] Sort Folders Before Files

```
/Users/denysbutenko/.atom/packages (31)
├── Sublime-Style-Column-Selection@1.2.3
├── advanced-new-file@0.3.3
├── atom-beautify@0.23.4
├── atom-color-highlight@3.0.8
├── auto-update-packages@0.2.2
├── autoclose-html@0.15.0
├── autocomplete-paths@1.0.2
├── autocomplete-plus@2.9.0
├── autohide-tree-view@0.16.3
├── close-tags@0.2.0
├── editorconfig@0.3.3
├── emmet@2.3.7
├── expand-selection-to-quotes@0.1.0
├── file-icons@1.5.4
├── html-entities@0.3.1
├── html-helper@0.2.3
├── html-img@0.3.2
├── javascript-snippets@1.0.0
├── language-nunjucks@1.3.0
├── language-smarty-php@0.5.0
├── linter@0.12.0
├── minimap@4.7.6
├── open-last-project@0.4.1
├── project-manager@1.15.5
├── project-switcher2@0.3.1
├── sassbeautify@0.2.0
├── seti-syntax@0.3.3
├── seti-ui@0.6.3
├── slash-closer@0.7.1
├── spacegray-eighties-dark-syntax@0.7.1
└── spacegray-eighties-ui@0.8.0
```

I tried install older version `@0.15.5` but still wrong working.

**Comment by olmokramer** [comment]
Aaaahhhh.... So it's nothing to do with OSX's window handling, but the `One Dark` UI theme. It adds a padding to the right side of the `atom-workspace` element, causing the tree view to not be on the edge of the screen... Expect a fix in a few minutes!

Thanks for being so helpful in identifying the problem :)

**Comment by olmokramer** [comment]
Wow... that was an easy fix :) New version is up!

**Comment by denysbutenko** [comment]
Thanks. It works properly now :)

**Comment by olmokramer** [comment]
This still happened in `v0.16.4` when the `pushEditor` setting was enabled. `v0.16.5` should fix that.
