### ISSUE TITLE
Tree view doesn't update

### ISSUE THREAD

**Issue by LaurentTreguier** [olmokramer/atom-autohide-tree-view#19]
Since v0.17, it seems the tree view doesn't update automatically anymore. For example, when adding a file to the tree view, it doesn't get added in the view until its containing folder has been folded/closed and then unfolded/opened. I don't remember seeing this behavior before v0.17. It's not very annoying, but seems a bit strange.
OS: Linux
Atom: 0.196
autohide-tree-view: 0.17.1

**Comment by olmokramer** [comment]
Hmm..... I've never seen this. How are you adding new files? By right clicking a folder in the tree view? Or by using a package (like advanced-new-file)? Or outside of atom?

**Comment by LaurentTreguier** [comment]
I add files by right clicking or with 'A' key when the tree view is focused. It happens when adding files, deleting them or moving them. I just tried re-installing (just to be sure), but that didn't do anything.

**Comment by olmokramer** [comment]
Does this also happen with all other packages disabled?

**Comment by LaurentTreguier** [comment]
Disabled all other packages, but that didn't change anything. I'm going to try on Windows and see if it's the same.

**Comment by LaurentTreguier** [comment]
Hey, it actually looks like it works fine on windows ! I wonder what could be the cause of the problem ? Perhaps it's something on my end... I always have at least one weird thing on my machine. I'll try some things, and see how it turns out.

**Comment by LaurentTreguier** [comment]
Well that was surely weird. I have the project-manager plugin installed. I have a few projects saved, but some of them were old ones that had a path leading to a non-existent directory. It resulted in an error thrown from the project-manager package each time Atom was opened. After I realized the cause, I cleaned my projects from the old ones. The error at Atom startup is gone now. And guess what ? This non-updating tree view is back to normal too. I'm not sure if I will ever understand this...

**Comment by olmokramer** [comment]
Haha, Atom and its quirks :p...

Definitely some weird stuff going on between project manager, this package and Atom... Nice you found the bug/a solution! :) I'll look into it and see what exactly is going wrong

**Comment by LaurentTreguier** [comment]
Also, I forgot to mention: I always used the project manager to quickly have a project open and test the tree view bug. That probably has a role in this... But it's still very odd

**Comment by olmokramer** [comment]
I tried, but wasn't able to reproduce this. Please let me know if it happens again :)
