### ISSUE TITLE
help avoid accidentally enabling the view?

### ISSUE THREAD

**Issue by mark-hahn** [olmokramer/atom-autohide-tree-view#2]
I'm not the most accurate mouser out there, but when I go to click on a line number I often overshoot briefly and the page moves to the right and I have to wait a second for the page to come back.  This is just an annoyance but enough of a pain for me to come here and take the trouble to type this out.  (grin)

This is a common situation on tooltip hovering on a webpage.  It is usually solved with a delay before activating but an even better fix is to wait until the mouse stops moving.  I would like to have one or both of these as options.

**Comment by olmokramer** [comment]
I wanted to go simple and use just CSS to accomplish the effect. Luckily there's such a thing as [transition-delay](https://developer.mozilla.org/en-US/docs/Web/CSS/transition-delay) to save the day! Expect a new version soon with a setting to adjust the delay :)
Thanks for taking the time to come here ant take the trouble to type this out! :P

**Comment by olmokramer** [comment]
New version 0.8.0 is out. It adds a new setting - Open Delay - that adjusts the delay before the menu opens.

**Comment by mark-hahn** [comment]
Thanks.  I'll check it out.
