### ISSUE TITLE
pin treeview feature?

### ISSUE THREAD

**Issue by huntertj** [olmokramer/atom-autohide-tree-view#20]
I would love to see the ability to pin the treeview by the push of a pinning button

**Comment by olmokramer** [comment]
What exactly do you mean by "pining"?

**Comment by huntertj** [comment]
Its a term from Visual Studio, sorry I should have been more specific.

Essentially a button in the pane of the treeview that turns autohide on/off 

Search "pin" on this page for a visual representation 
https://msdn.microsoft.com/en-us/library/windows/apps/dn263225.aspx

**Comment by olmokramer** [comment]
Ah.. Makes sense :p Thanks for explaining.

I'm working on a new version that includes enable/disable commands to enable/disable autohide behaviour, so adding a button should be easy. I'll probably put it behind a config, though. I like my keybindings :p

**Comment by huntertj** [comment]
:+1:

**Comment by olmokramer** [comment]
Hey, I'm sorry it took so long, but I implemented this feature today. It will be included in the next release, which should be over the next few days.

**Comment by olmokramer** [comment]
The new version is published now. Please let me know what you think :)

**Comment by denysbutenko** [comment]
:+1: Thanks, it's helpful feature!
There an issue when toggling "Pin" with disabled option "Push Editor".

**Comment by olmokramer** [comment]
Yeah, I noticed that it doesn't look very pretty. I'll look into a way to make it look a little better :) Thanks!

**Comment by huntertj** [comment]
:+1: great feature add, ditto on the prettying it up :)

**Comment by ProLoser** [comment]
This feature is awesome, however the panel does not autogrow when pinned.

**Comment by olmokramer** [comment]
Ok, I did some work to make it look better. I'll test a bit more tomorrow and then I'll release version 0.23.0. I think I can close this issue then :)

**Comment by olmokramer** [comment]
I just released v0.23.0 with a pretty animation when pinning :) Let me know what you think!

**Comment by olmokramer** [comment]
Ok, I'll close this, as I've heard no one complain in a while :) Thanks for the feedback everyone!
