### ISSUE TITLE
Request: Disable autohide if window exceeds custom width

### ISSUE THREAD

**Issue by colemickens** [olmokramer/atom-autohide-tree-view#21]
Hello!

This plugin is great for when I have atom taking up half of my display. However, when I have it fullscreen, I before to have the plugin disabled.

Would it be possible to disable the auto-hiding if the window exceeds a certain width?

**Comment by olmokramer** [comment]
Thanks for the suggestion! I like it :)

I'm in the middle of a huge update, though, so it might take a few days before it's published.

**Comment by olmokramer** [comment]
Ok it was quite easy to implement this :) I need to fix a few bugs, and then it can go live!

**Comment by olmokramer** [comment]
Alright, the new version is up! Please let me know if you have any issues

**Comment by colemickens** [comment]
Works perfectly. Thank you!
