### ISSUE TITLE
Autohide does not render properly when it is opened using the Reveal on Tree View option 

### ISSUE THREAD

**Issue by m4rc3iro** [olmokramer/atom-autohide-tree-view#22]
**Steps to reproduce**
1. right click on a source file and click on the Reveal on Tree View option
2. tree view slides out but its content is not rendered properly

**Notes**: Disable/enable the plugin for it to work properly again.

**Comment by olmokramer** [comment]
Hey, thanks for submitting the issue! :)

For me, the reveal in tree view command _does_ show the content of the tree view, but it doesn't expand to full width (cutting off some of the text), so it's definitely buggy... I'll try to give this a look this weekend, but it might take another week.

Cheers,

**Comment by m4rc3iro** [comment]
no worries mate, u did an excellent job with the plug-in.

another thing I've noticed is that there is a settings button but it
doesn't do anything. is that intended?

if not, perhaps u could make the slide out speed user configurable, that
would be cool to have :)

**Comment by olmokramer** [comment]
Hey, I just changed some code regarding the reveal in tree view command, and published it as v0.20.1. Could you please check if it solves your problems with that? Thanks!

About the settings button, what button are you talking about? Can you maybe make a screenshot?

**Comment by m4rc3iro** [comment]
hi olmo, I just tested it out this morning and everything works ok.

Thanks very much!

**Comment by olmokramer** [comment]
Alright awesome!
