### ISSUE TITLE
leaving window doesn't work

### ISSUE THREAD

**Issue by mark-hahn** [olmokramer/atom-autohide-tree-view#23]
If I move the mouse out of Atom's window to the left then after the hover delay setting the tree shows and stays visible.  This happens when the time to pass over the border is much less than the hover delay.  This means that when I have a window to the left of Atom and go back and forth the tree is in the way much of the time.

I have had behavior problems like this on web projects in the past.  It is solvable.

**Comment by olmokramer** [comment]
Thanks for submitting the issue. I'll see what I can do, but it does strike me as odd; the tree view should hide on a mouseleave event (which I assume to be triggered when the mouse leaves the window)

**Comment by olmokramer** [comment]
I can't reproduce this. If you edit `lib/autohide-tree-view.js` to `console.log` something on line `108`, does it actually log that when the mouse leaves the window?

**Comment by mark-hahn** [comment]
I think I understand this now.  I'm running Atom in an X server window, not in a desktop.  I suspect the window can't report a mouse value smaller than zero.  So the mouse in atom never actually leaves the window.  I posted an issue on the chromebook crouton repo about this.

https://github.com/dnschneid/crouton/issues/1866

**Comment by olmokramer** [comment]
Ah that makes a lot of sense! Thanks for letting me know about this.
