### ISSUE TITLE
Allow me to customize the hover zone

### ISSUE THREAD

**Issue by ProLoser** [olmokramer/atom-autohide-tree-view#25]
It would be nice to manually adjust the Hover Area Size and not just the Touch Area Size.

**Comment by ProLoser** [comment]
Okay I just realized this is `Hidden Width`. Is there any chance you could make this side bar invisible (like 0 width) and have an invisible hover zone that extends out into the editor pane? This way increasing the hover zone does not decrease the size of the editor pane.

**Comment by olmokramer** [comment]
Hi, yes indeed the `hiddenWidth` config is for this.

Allowing to set it to `0` would add a lot of complexity, so I don't know if I want to support this. I'll think about it and see if I can come up with a simpler solution. I've set `hiddenWidth` to `1`, and the tree view is barely visible.

**Comment by ProLoser** [comment]
So yeah i was thinking just make it 1px but then make the hoverable-area bigger. Like you don't have to move the mouse over the actual gutter. But I switched up my window arrangement a bit and i don't find this as pressing of an issue anymore (before, the mouse would move past the edge of the window, but I reoriented the file tree so I can push the mouse to the edge of the screen).

**Comment by olmokramer** [comment]
Ah I see. That would be nice! I'll look into implementing it in a while.

**Comment by olmokramer** [comment]
I just implemented this. There's a new setting, `hoverAreaSize`, that sets the width of an invisible area on the edge of the screen that you can hover (or click) to show the tree view. You can also set `hiddenWidth` to `0` now. I'll release this tomorrow, after I can get some more testing done.

**Comment by olmokramer** [comment]
Hey, I just published the new version. Please let me know what you think!
