### ISSUE TITLE
Cannot shrink the hidden width to below 100px after 0.20.3 update.

### ISSUE THREAD

**Issue by FossPrime** [olmokramer/atom-autohide-tree-view#27]
Setting the Hidden width any lower will not yield any results.

**Comment by olmokramer** [comment]
Hey, thanks for the report. I will look into this tonight or tomorrow.

**Comment by FossPrime** [comment]
Never mind! Upgraded Atom to the latest version and now it's working normally. Can't remember what version I upgraded from.  It's not in my yum log.

**Comment by olmokramer** [comment]
Awesome! Saves me some frustration ;) Thanks for letting me know
