### ISSUE TITLE
I am getting a lot of incorrectly scrolled container bugs when reveal is called.

### ISSUE THREAD

**Issue by ProLoser** [olmokramer/atom-autohide-tree-view#34]
![screen shot 2015-07-27 at 1 22 32 pm](https://cloud.githubusercontent.com/assets/67395/8916774/937508bc-3462-11e5-9917-3c09a7c291b4.png)
Pinning seems to fix this, but it's borked if you call reveal in tree (and plugins that do this for you.

**Comment by ProLoser** [comment]
I think you just need to add horizontal scrolling in ADDITION to vertical scrolling, and the pin should be fixed or something if possible.

**Comment by ProLoser** [comment]
Did some poking around:

```
.tree-view-resizer {
  max-width: 300px; // make this configurable
}
.tree-view-scroller {
  overflow-x: inherit; // this property should just be removed
}
.selected::before {
  min-width: none; // this property should just be removed
}
```

I would just come up with an alternative approach for placing the pin, but still allow the tree to expand and scroll about normally. You might also want to set a max-width for it to expand to and allow me to customize this.

**Comment by olmokramer** [comment]
Ok, the new version is up. It fixes a lot of things including this one. Please let me know if everything works.

**Comment by olmokramer** [comment]
So is this working correctly now?
