### ISSUE TITLE
Panel won't hide

### ISSUE THREAD

**Issue by ProLoser** [olmokramer/atom-autohide-tree-view#39]
I have to like pin it and then unpin it. And it's sorta huge (cuz I have a deep tree) so it takes up a LOT of room. It's also slightly impossible to tell if it's pinned or not because the pin icon doesn't change at all. You should have an outline version and a filled version (I find the diagonal pin vs vertical pin differentiation isn't very helpful).

This seems to happen extremely consistently every time I open a new file. I also use this plugin which may be conflicting? https://atom.io/packages/auto-reveal-in-sidebar

**Comment by olmokramer** [comment]
This is actually related to the issues in #38 and #40. I'll publish a new version in a few minutes, please let me know if it works.

About the pin icon, I've opened a new issue for that: #41

**Comment by Gibbz** [comment]
this works on my linux machine, but the pin icon and all that is not working on my windows machine :(

**Comment by olmokramer** [comment]
@Gibbz Could you please be a bit more specific? What exactly doesn't work, when does and when doesn't it work? Also, what version of Atom, autohide-tree-view and OS are you using?

**Comment by Gibbz** [comment]
It started working after a restart, so it all good now

**Comment by olmokramer** [comment]
:+1: Awesome!
