### ISSUE TITLE
close delay same as open

### ISSUE THREAD

**Issue by mark-hahn** [olmokramer/atom-autohide-tree-view#4]
The open delay (thanks) is unfortunately also used as a close delay.  Ideally I'd like the close to happen instantly even though the open is at 1 second.

I would like to do a PR but I've never done CSS animations before.  Maybe this is a good time to learn.

**Comment by olmokramer** [comment]
Hmmm... That's too bad. I'll take a look at it tonight (european time)

**Comment by olmokramer** [comment]
I just published `v0.10.0` which should fix your issues. It's become a complete rewrite, but in the end it was worth it. Much better control over the delays now

**Comment by mark-hahn** [comment]
> . It's become a complete rewrite

Sorry to cause so much trouble.

**Comment by olmokramer** [comment]
Not a problem at all! In the end the package has improved. Hope you like the changes

I love your `sub-atom` package by the way, it was very useful for this one!
