### ISSUE TITLE
Better pinned/unpinned icon differentiation

### ISSUE THREAD

**Issue by olmokramer** [olmokramer/atom-autohide-tree-view#41]
The pin icon changes colour when it is pinned, but it could be better. #39 proposes an outline vs a filled version, for example. I'll explore some possibilities here.

I'm currently using the octicon font that's shipped with Atom for the pin icon, and it doesn't provide an outline version, and I'm kind of reluctant to move to another font... Maybe it's possible with CSS `text-shadow`. I'll look into that.

**Comment by larsenwork** [comment]
You can probably just use `-webkit-text-stroke`

**Comment by D-side** [comment]
Rotation is also a possibility. [Here's how FontAwesome](https://github.com/FortAwesome/Font-Awesome/blob/master/less/mixins.less#L14) has done it. Rotation 45 degrees clockwise is a noticeable change.

@ProLoser (author of #39) claims that rotation only is not too helpful, so combining it with some other effect is probably better.

**Comment by ProLoser** [comment]
I am fine with just rotation as it's better than nothing

**Comment by olmokramer** [comment]
@larsenwork I've never heard of `-webkit-text-stroke`, awesome!

I've done a mix of both a rotated and an outlined icon. Will be included in the next version. Thanks for the suggestions!

**Comment by olmokramer** [comment]
The new version that includes this is up. Please let me know what you think
