### ISSUE TITLE
Error messages at startup

### ISSUE THREAD

**Issue by rugk** [olmokramer/atom-autohide-tree-view#44]
Just when starting Atom (Okay, it can be I already hovered one time over the tree view) I get the following error messages:
![autohidetreeview](https://cloud.githubusercontent.com/assets/11966684/9232349/78be6608-412d-11e5-9392-837c5a24294d.PNG)

Okay I think in this format they are more readable:
![autohidetreeview2](https://cloud.githubusercontent.com/assets/11966684/9232365/92c24c90-412d-11e5-93b1-4be0d31a437d.PNG)

0.24.0
Atom 1.0.6

**Comment by olmokramer** [comment]
Hi, thanks for the report. I'm on vacation right now, so unfortunately (well, for you, I'm quite enjoying it! :) I can't work on it now. I'll look at it when I'm back.

**Comment by D-side** [comment]
Hi! I just dug around this bug. Try switching the tree view to show on `hover` (`hover+touch` seems to be default) in package configuration. Or any other option that does not involve `touch`.

If that causes the error to disappear (restart and look at the log), it's a duplicate of #32.

**Comment by rugk** [comment]
Yes this fixes it. (Although I was on hover+click+touch before)

**Comment by olmokramer** [comment]
@D-side suspicions were correct. I forgot to check if [atom-touch-events](https://atom.io/packages/atom-touch-events) was installed/enabled. A new version will be up in a few minutes :)

**Comment by rugk** [comment]
Yes with v 0.24.2 this error messages are not shown any more.

**Comment by olmokramer** [comment]
Awesome!
