### ISSUE TITLE
Don't show tree-view when text selection is in progresss

### ISSUE THREAD

**Issue by notreadbyhumans** [olmokramer/atom-autohide-tree-view#46]
When text selection is in progress - mouse down and dragging the cursor - and the pointer goes over the hoverarea, the tree-view is exposed.

Would it be possible to exclude hover events when a click is already in progress?

**Comment by olmokramer** [comment]
Thanks for the report. It should already be doing this. Can you provide the autohide-tree-view settings and a list of packages you're using?

**Comment by notreadbyhumans** [comment]
I can confirm that this is now working as expected, not sure whether I was using an old version, etc.

**Comment by olmokramer** [comment]
Awesome! Thanks.
