### ISSUE TITLE
Settings are gone

### ISSUE THREAD

**Issue by ProLoser** [olmokramer/atom-autohide-tree-view#48]
Don't know how to get to the settings anymore as the button in the package list is gone.

**Comment by olmokramer** [comment]
Is it only this package? All the settings seem to work fine for me...

**Comment by ProLoser** [comment]
Sorry I mean that the button is missing in the packages list. I thought I remembered one being there. You should consider adding a settings button

**Comment by ProLoser** [comment]
Nvm I think this was on the install page

**Comment by olmokramer** [comment]
Hmm.. It should still show a settings button, also on the install page. It's not something I can controll, though. If it keeps happening you should post an issue on [settings-view](https://github.com/atom/settings-view).
