### ISSUE TITLE
Pinned Tree View hides after pressing Alt

### ISSUE THREAD

**Issue by feimosi** [olmokramer/atom-autohide-tree-view#50]
When you press Alt to invoke Atom's menu-bar and have Tree View pinned with the special button, it hides itself and becomes unpinned (the icon remains unchanged)

Package version: 0.24.3
Atom 1.0.11

**Comment by olmokramer** [comment]
Thanks for reporting the issue. I can reproduce the behavior. Really weird! I'll look into it

**Comment by olmokramer** [comment]
I've found the issue. The package was listening to window resizes for the `maxWindowWidth` setting. Showing/hiding the menu bar changes window size, and apparently it hid the tree view when it was visible. The fix will be included in the next release.

**Comment by feimosi** [comment]
That's great, thanks for a quick response!

**Comment by olmokramer** [comment]
I've just published the new version. I'm sorry it took so long, #28 has been holding it back for about a week. Please let me know if it resolves your issues.

**Comment by feimosi** [comment]
I can confirm the issue is fixed. Thanks once again.

**Comment by olmokramer** [comment]
You're welcome :)
