### ISSUE TITLE
Don't hide when no files are open

### ISSUE THREAD

**Issue by lukescott** [olmokramer/atom-autohide-tree-view#52]
I opened a project using an Alfred workflow and was confused when the window was empty. I then realized that it wasn't, I just needed to open a file. The tree view probably shouldn't be hidden if no files are open yet.

**Comment by olmokramer** [comment]
Nice one, thanks for the suggestion! I think I like it :) I'll include this in v0.25.0, but first I want to get v0.24.4 published once #28 seems resolved.

**Comment by olmokramer** [comment]
Just implemented the feature. It's on the master branch, in case you want to try it out :)

**Comment by lukescott** [comment]
The first time I did it the width was off. I can't seem to reproduce that though. Works great!

**Comment by olmokramer** [comment]
Hi, I just published v0.25.0 that includes this. It seems I don't have a lot of time in the near future, so I just wanted to get this out.
