### ISSUE TITLE
No matching commands in the command palette

### ISSUE THREAD

**Issue by jesperbjerke** [olmokramer/atom-autohide-tree-view#7]
therefor, I cannot activate the plugin and nothing happens

**Comment by olmokramer** [comment]
I think this is duplicate of https://github.com/olmokramer/atom-autohide-tree-view/issues/6 . I'll take a look at it tonight

**Comment by olmokramer** [comment]
Does the 0.13.0 version fix the problem for you?

**Comment by jesperbjerke** [comment]
Yep, thanks!

**Comment by olmokramer** [comment]
You're welvome :)
