### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by shlomiLan** [olmokramer/atom-autohide-tree-view#93]
I'm using version 0.25.1 with Atom 1.27.2 on a mac. I have tried to also install `atom-touch-events` but it doesn't seem to have any effect.

**Comment by sanarena** [comment]
I've created this simple package to be able do my daily tasks without file tree annoyance for now, far from original plugin but it just works: https://atom.io/packages/filetree-autohide

**Comment by shlomiLan** [comment]
It seems to work fine. Thanks.
